### ISSUE TITLE
Bug when saving/loading an empty String

### ISSUE THREAD

**Issue by tomasherman** [paradigmatic/Configrity#13]
Hey there, it looks like I found another bug. It seems like configrity saves empty string like so:

```
 some.key = 
```

but isn't able to parse such format. It throws following error:

```
! org.streum.configrity.io.StandardFormat$ParserException: [7.12] failure: `}' expected but `=' found
! 
!   password = 
! 
!            ^
!   at org.streum.configrity.io.StandardFormat$Parser$class.parse(StandardFormat.scala:78)
```

Adding manually " " into config file resolves the issue.

**Comment by paradigmatic** [comment]
Thanks for reporting the bug, it's a good catch. I've committed a fix in the master branch (with more tests). I will release a new version this week-end.
