### ISSUE TITLE
YAML format

### ISSUE THREAD

**Issue by slavus** [paradigmatic/Configrity#2]
Please add  support for YAML as configuration Format.

**Comment by paradigmatic** [comment]
I will be happy to add YAML format. Just a few questions to understand more precisely what you are looking for:
1. Do you need YAML as input format (a YAML file can be loaded in a Configuration), output format (Configuration can be saved as YAML), or both ?
2. Which YAML 1.1 features you think are essential ? Scalar and collections can be implemented easily but anchors, tags, etc. will require either more work.

The less features you ask, the soonest I may do the job ;-)

**Comment by slavus** [comment]
1. reading from YAML is a must(input) , writing to it(output) would be nice.
2. I think Scalar and collections are enough.

**Comment by paradigmatic** [comment]
I have enough time to work on the YAML format for Configrity and I hope to finish it before Christmas. I will use SnakeYAML for the actual YAML parsing.

As I want Configrity to remain without external dependencies, I chose a modular architecture. You can have a look at the work in progress, in branch `modular`. The YAML plugin is in the `modules/yaml` directory. Of course, you can contribute...

**Comment by slavus** [comment]
It looks good. I like modular design, it is good that you don't introduce  external dependencies if you don't want to use yaml. Thanx

**Comment by paradigmatic** [comment]
I commited the YAML module to the v0.10.0. See: https://github.com/paradigmatic/Configrity/wiki/YAML for usage.
