### ISSUE TITLE
Release for Scala 2.10.0

### ISSUE THREAD

**Issue by akisaarinen** [paradigmatic/Configrity#21]
There doesn't seem to be a Configrity release for Scala 2.10.0.

Scala 2.10 has not been announced publicly, but it has already been released to
Typesafe repositories so that library authors can make a version of their library
available for 2.10 prior to its public announcement. This makes the release process
go smoother (and people will be happier to upgrade).

It woud be great to have a release of Configrity for Scala 2.10 available as well.

**Comment by paradigmatic** [comment]
I just published Configrity 1.0.0 with support for Scala 2.10.0.

**Comment by akisaarinen** [comment]
Excellent, thank you!
