### ISSUE TITLE
Please allow native Scala List for values

### ISSUE THREAD

**Issue by nermin** [paradigmatic/Configrity#4]
To configure a value in the code which represents a List we have to write something like this:

val config = Configuration(
  ...
  "some.key.1" -> "[10]"
  "some.key.2" -> "[\"some string\"]"
  ...
)

which looks ugly. What I would like to do is this:

val config = Configuration(
  ...
  "some.key.1" -> List(10)
  "some.key.2" -> "some string" :: Nil
  ...
)

Thanks!

**Comment by paradigmatic** [comment]
I just added the feature you requested in the master branch. Can you please test it and tell me if it fits your needs ?

Please note that the syntax:

```
val config = Configuration(
  "some.key.2" -> "some string" :: Nil
)
```

won't work because `->` has a higher priority than `::`. You will need parenthesis:

```
val config = Configuration(
  "some.key.2" -> ( "some string" :: Nil )
)
```

**Comment by nermin** [comment]
Just tested, it works. Thank you!
